.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hyprnome 1  "hyprnome 0.1.0" 
.SH NAME
hyprnome \- GNOME\-like workspace switching in Hyprland.
.SH SYNOPSIS
\fBhyprnome\fR [\fB\-a\fR|\fB\-\-allow\-going\-backwards\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
.PP
hyprnome is a program that enables you to achieve GNOME\-like workspace switching in Hyprland.
.PP
Unlike Hyprland\*(Aqs r+1/r\-1, empty workspaces are not shown to the user when the user navigates
between them.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-allow\-going\-backwards\fR
Create empty workspaces when going backwards
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show information about what hyprnome is doing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
.SH AUTHORS
Copyright (C) 2023 Donovan Glover <https://donovan.is/>
