.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hyprnome 1  "hyprnome 0.1.0" 
.SH NAME
hyprnome \- GNOME\-like workspace switching in Hyprland.
.SH SYNOPSIS
\fBhyprnome\fR [\fB\-p\fR|\fB\-\-previous\fR] [\fB\-n\fR|\fB\-\-no\-empty\-before\fR] [\fB\-N\fR|\fB\-\-no\-empty\-after\fR] [\fB\-m\fR|\fB\-\-move\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
.PP
hyprnome is a program that enables you to achieve GNOME\-like workspace switching in Hyprland.
.PP
Unlike Hyprland\*(Aqs r+1/r\-1, empty workspaces between two occupied workspaces are skipped.
.PP
Unlike Hyprland\*(Aqs m+1/m\-1, new workspaces are created instead of wrapping to existing ones.
.PP
Example hyprland.conf:
.PP
bind = $SUPER, 1, exec, hyprnome \-\-previous
.PP
bind = $SUPER, 2, exec, hyprnome
.PP
bind = $SUPER_SHIFT, 1, exec, hyprnome \-\-previous \-\-move
.PP
bind = $SUPER_SHIFT, 2, exec, hyprnome \-\-move
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-previous\fR
Go to the previous workspace instead of the next
.TP
\fB\-n\fR, \fB\-\-no\-empty\-before\fR
Don\*(Aqt create empty workspaces to the left
.TP
\fB\-N\fR, \fB\-\-no\-empty\-after\fR
Don\*(Aqt create empty workspaces to the right
.TP
\fB\-m\fR, \fB\-\-move\fR
Move the active window to the dispatched workspace
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print debugging information
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
.SH AUTHORS
Copyright (C) 2023 Donovan Glover <https://donovan.is/>
