[package]
name = "hyprnome"
description = "GNOME-like workspace switching in Hyprland."
version = "0.1.0"
authors = ["Copyright (C) 2023 Donovan Glover <https://donovan.is/>"]
repository = "https://github.com/donovanglover/hyprnome"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
hyprland = "0.3.12"

[build-dependencies]
clap = { version = "4.4.6", features = ["derive"] }
clap_complete = "4.4.3"
clap_mangen = "0.2.14"

[dev-dependencies]
assert_cmd = "2.0.12"
rustympkglib = "0.1.1"
serde = "1.0.189"
toml = "0.8.2"
