[package]
name = "hyprnome"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }
hyprland = "0.3.9"

[build-dependencies]
clap = { version = "4.4.1", features = ["derive"] }
clap_complete = "4.4.0"
clap_mangen = "0.2.13"
