complete -c hyprnome -s p -l previous -d 'Go to the previous workspace instead of the next'
complete -c hyprnome -s n -l no-empty-before -d 'Don\'t create empty workspaces to the left'
complete -c hyprnome -s N -l no-empty-after -d 'Don\'t create empty workspaces to the right'
complete -c hyprnome -s m -l move -d 'Move the active window to the dispatched workspace'
complete -c hyprnome -s v -l verbose -d 'Print debugging information'
complete -c hyprnome -s h -l help -d 'Print help (see more with \'--help\')'
complete -c hyprnome -s V -l version -d 'Print version'
